const AUTO_GENERATED_NAME_PATTERNS = [
  /^new chat$/i,
  /^untitled(?: chat)?$/i,
  /^chat\s+\d/i,
  /^chat\s+\d{1,2}[/-]\d{1,2}[/-]\d{2,4}/i,
  /^conversation\s+\d/i,
];

const LEADING_FILLER_REGEX = /^(please\s+|can you\s+|could you\s+|help me\s+|i want to\s+|i need to\s+|let'?s\s+|build\s+me\s+|create\s+me\s+|make\s+me\s+)/i;
const LEADING_ACTION_REGEX = /^(build|create|make|design|generate|write|fix|update|improve|scrape|find|show)\s+(?:a|an|the\s+)?/i;
const PAGE_TYPE_REGEX = /(landing page|website|dashboard|app|form|workflow|automation|search|scraper|funnel|page)/i;

const sanitizeConversationPrompt = (content: string) =>
  content
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/https?:\/\/\S+/g, ' ')
    .replace(/[>#*_`~\[\]()]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

const formatWord = (word: string) => {
  if (!word) return word;
  if (/^[A-Z0-9-]+$/.test(word) || /[A-Z].*[A-Z]/.test(word)) return word;
  if (/^[a-z]/.test(word)) return word.charAt(0).toUpperCase() + word.slice(1);
  return word;
};

const toTitleCase = (value: string) => value.split(/\s+/).map(formatWord).join(' ').trim();

const truncateTitle = (value: string, maxLength = 48) =>
  value.length > maxLength ? `${value.slice(0, maxLength - 1).trimEnd()}…` : value;

export const isAutoGeneratedConversationName = (name: string | null | undefined) => {
  const normalized = name?.trim();
  if (!normalized) return true;
  return AUTO_GENERATED_NAME_PATTERNS.some((pattern) => pattern.test(normalized));
};

export const generateConversationTitle = (firstUserMessage: string) => {
  const cleaned = sanitizeConversationPrompt(firstUserMessage);
  if (!cleaned) return 'New Chat';

  const pageTypeMatch = cleaned.match(PAGE_TYPE_REGEX);
  const subjectMatch = cleaned.match(/\b(?:for|about)\s+(.+)$/i);

  if (pageTypeMatch && subjectMatch?.[1]) {
    const subject = truncateTitle(toTitleCase(subjectMatch[1].trim()));
    const pageType = toTitleCase(pageTypeMatch[1]);

    if (subject) {
      return truncateTitle(`${subject} ${pageType}`);
    }
  }

  const withoutCommand = cleaned.replace(/^\/\w+\s+/, '');
  const withoutFiller = withoutCommand.replace(LEADING_FILLER_REGEX, '');
  const simplified = withoutFiller.replace(LEADING_ACTION_REGEX, '').trim();
  const words = simplified.split(/\s+/).filter(Boolean).slice(0, 6);
  const title = toTitleCase(words.join(' ').replace(/\b(for|with|using|from|into)\b\s*$/i, '').trim());

  return truncateTitle(title || toTitleCase(cleaned.split(/\s+/).slice(0, 6).join(' ')) || 'New Chat');
};