project_id = "tiqrilqdnjcwxxmcewca"

[functions.chat]
verify_jwt = false

[functions.browser-task]
verify_jwt = false

[functions.stop-browser-task]
verify_jwt = false

[functions.pause-browser-task]
verify_jwt = false

[functions.resume-browser-task]
verify_jwt = false

[functions.manage-profile]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.browser-task-webhook]
verify_jwt = false

[functions.ghl-contact-webhook]
verify_jwt = false

[functions.create-google-sheet]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.share-preview]
verify_jwt = false
