import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';
import { generateConversationTitle, isAutoGeneratedConversationName } from '@/lib/conversationTitles';

export interface Conversation {
  id: string;
  name: string;
  description: string | null;
  created_at: string;
  updated_at: string;
}

export const useConversations = () => {
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const { user } = useAuth();
  const { toast } = useToast();

  const backfillConversationTitles = async (items: Conversation[]) => {
    if (!user || items.length === 0) return items;

    const untitledConversationIds = items
      .filter((conversation) => isAutoGeneratedConversationName(conversation.name))
      .map((conversation) => conversation.id);

    if (untitledConversationIds.length === 0) return items;

    const { data, error } = await supabase
      .from('messages')
      .select('project_id, content, created_at')
      .eq('user_id', user.id)
      .eq('role', 'user')
      .in('project_id', untitledConversationIds)
      .order('created_at', { ascending: true });

    if (error) {
      console.error('Error backfilling conversation titles:', error);
      return items;
    }

    const firstMessageByProject = new Map<string, string>();

    for (const message of data || []) {
      if (message.project_id && message.content && !firstMessageByProject.has(message.project_id)) {
        firstMessageByProject.set(message.project_id, message.content);
      }
    }

    const updatedConversations = items.map((conversation) => {
      const firstMessage = firstMessageByProject.get(conversation.id);
      if (!firstMessage) return conversation;

      return {
        ...conversation,
        name: generateConversationTitle(firstMessage),
      };
    });

    const conversationsToPersist = updatedConversations.filter(
      (conversation, index) => conversation.name !== items[index].name
    );

    if (conversationsToPersist.length > 0) {
      await Promise.allSettled(
        conversationsToPersist.map((conversation) =>
          supabase
            .from('projects')
            .update({ name: conversation.name })
            .eq('id', conversation.id)
            .eq('user_id', user.id)
        )
      );
    }

    return updatedConversations;
  };

  const fetchConversations = async () => {
    if (!user) {
      setConversations([]);
      setIsLoading(false);
      return;
    }
    
    setIsLoading(true);
    const { data, error } = await supabase
      .from('projects')
      .select('*')
      .eq('user_id', user.id)
      .order('updated_at', { ascending: false });

    if (error) {
      console.error('Error fetching conversations:', error);
      toast({
        title: "Error loading conversations",
        description: error.message,
        variant: "destructive",
      });
    } else {
      const titledConversations = await backfillConversationTitles(data || []);
      setConversations(titledConversations);
    }
    setIsLoading(false);
  };

  useEffect(() => {
    fetchConversations();
  }, [user]);

  const createConversation = async (name?: string) => {
    if (!user) return null;

    const conversationName = name || `New Chat`;
    
    const { data, error } = await supabase
      .from('projects')
      .insert({
        name: conversationName,
        user_id: user.id,
        description: 'New conversation',
      })
      .select()
      .single();

    if (error) {
      console.error('Error creating conversation:', error);
      toast({
        title: "Error creating conversation",
        description: error.message,
        variant: "destructive",
      });
      return null;
    }

    setConversations(prev => [data, ...prev]);
    toast({
      title: "Conversation created",
      description: conversationName,
    });
    
    return data;
  };

  const deleteConversation = async (id: string) => {
    if (!user) return;

    const { error } = await supabase
      .from('projects')
      .delete()
      .eq('id', id)
      .eq('user_id', user.id);

    if (error) {
      console.error('Error deleting conversation:', error);
      toast({
        title: "Error deleting conversation",
        description: error.message,
        variant: "destructive",
      });
    } else {
      setConversations(prev => prev.filter(c => c.id !== id));
      toast({
        title: "Conversation deleted",
      });
    }
  };

  const renameConversation = async (id: string, newName: string) => {
    if (!user) return;

    const { error } = await supabase
      .from('projects')
      .update({ name: newName })
      .eq('id', id)
      .eq('user_id', user.id);

    if (error) {
      console.error('Error renaming conversation:', error);
      toast({
        title: "Error renaming conversation",
        description: error.message,
        variant: "destructive",
      });
    } else {
      setConversations(prev =>
        prev.map(c => (c.id === id ? { ...c, name: newName } : c))
      );
      toast({
        title: "Conversation renamed",
      });
    }
  };

  const autoTitleConversation = async (id: string, firstUserMessage: string) => {
    if (!user) return;

    const currentConversation = conversations.find((conversation) => conversation.id === id);
    if (currentConversation && !isAutoGeneratedConversationName(currentConversation.name)) {
      return;
    }

    const shortTitle = generateConversationTitle(firstUserMessage);
    if (!shortTitle) return;

    const { error } = await supabase
      .from('projects')
      .update({ name: shortTitle })
      .eq('id', id)
      .eq('user_id', user.id);

    if (error) {
      console.error('Error auto-titling conversation:', error);
      return;
    }

    setConversations((prev) =>
      prev.map((conversation) => (conversation.id === id ? { ...conversation, name: shortTitle } : conversation))
    );
  };

  return {
    conversations,
    isLoading,
    createConversation,
    deleteConversation,
    renameConversation,
    autoTitleConversation,
    refreshConversations: fetchConversations,
  };
};
