import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';
import { isAutoGeneratedConversationName } from '@/lib/conversationTitles';

export interface Conversation {
  id: string;
  name: string;
  description: string | null;
  created_at: string;
  updated_at: string;
}

export const useConversations = () => {
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const { user } = useAuth();
  const { toast } = useToast();
  const userId = user?.id ?? null;

  const fetchConversations = useCallback(async () => {
    if (!userId) {
      setConversations([]);
      setIsLoading(false);
      return;
    }

    setIsLoading(true);
    const { data, error } = await supabase
      .from('projects')
      .select('*')
      .eq('user_id', userId)
      .order('updated_at', { ascending: false });

    if (error) {
      console.error('Error fetching conversations:', error);
      toast({
        title: "Error loading conversations",
        description: error.message,
        variant: "destructive",
      });
    } else {
      setConversations(data || []);
    }
    setIsLoading(false);
  }, [userId, toast]);

  // Initial fetch + realtime subscription
  useEffect(() => {
    fetchConversations();

    if (!userId) return;

    const channel = supabase
      .channel('conversations-realtime')
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'projects',
          filter: `user_id=eq.${userId}`,
        },
        (payload) => {
          if (payload.eventType === 'INSERT') {
            const newConv = payload.new as Conversation;
            setConversations((prev) => {
              if (prev.some((c) => c.id === newConv.id)) return prev;
              return [newConv, ...prev];
            });
          } else if (payload.eventType === 'UPDATE') {
            const updated = payload.new as Conversation;
            setConversations((prev) =>
              prev.map((c) => (c.id === updated.id ? updated : c))
            );
          } else if (payload.eventType === 'DELETE') {
            const deletedId = payload.old?.id;
            if (deletedId) {
              setConversations((prev) => prev.filter((c) => c.id !== deletedId));
            }
          }
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [userId, fetchConversations]);

  const createConversation = async (name?: string) => {
    if (!user) return null;

    const conversationName = name || 'New Chat';

    const { data, error } = await supabase
      .from('projects')
      .insert({
        name: conversationName,
        user_id: user.id,
        description: 'New conversation',
      })
      .select()
      .single();

    if (error) {
      console.error('Error creating conversation:', error);
      toast({
        title: "Error creating conversation",
        description: error.message,
        variant: "destructive",
      });
      return null;
    }

    // Realtime will handle adding it to the list
    return data;
  };

  const deleteConversation = async (id: string) => {
    if (!user) return;

    // Optimistically remove from UI immediately
    setConversations((prev) => prev.filter((c) => c.id !== id));

    // Delete associated messages first
    await supabase
      .from('messages')
      .delete()
      .eq('project_id', id)
      .eq('user_id', user.id);

    const { error } = await supabase
      .from('projects')
      .delete()
      .eq('id', id)
      .eq('user_id', user.id);

    if (error) {
      console.error('Error deleting conversation:', error);
      toast({
        title: "Error deleting conversation",
        description: error.message,
        variant: "destructive",
      });
      // Re-fetch to restore if delete failed
      fetchConversations();
    }
  };

  const renameConversation = async (id: string, newName: string) => {
    if (!user) return;

    const { error } = await supabase
      .from('projects')
      .update({ name: newName })
      .eq('id', id)
      .eq('user_id', user.id);

    if (error) {
      console.error('Error renaming conversation:', error);
      toast({
        title: "Error renaming conversation",
        description: error.message,
        variant: "destructive",
      });
    }
    // Realtime will handle updating the list
  };

  const autoTitleConversation = async (id: string, firstUserMessage: string) => {
    if (!user) return;

    const currentConversation = conversations.find((c) => c.id === id);
    if (currentConversation && !isAutoGeneratedConversationName(currentConversation.name)) {
      return;
    }

    try {
      // Call the AI-powered title generation edge function
      const { data, error } = await supabase.functions.invoke('generate-title', {
        body: { message: firstUserMessage, conversationId: id },
      });

      if (error) {
        console.error('Error auto-titling conversation:', error);
        return;
      }

      // The edge function updates the DB directly, and realtime will propagate the change.
      // But also update local state immediately for responsiveness.
      if (data?.title) {
        setConversations((prev) =>
          prev.map((c) => (c.id === id ? { ...c, name: data.title } : c))
        );
      }
    } catch (err) {
      console.error('Error auto-titling conversation:', err);
    }
  };

  return {
    conversations,
    isLoading,
    createConversation,
    deleteConversation,
    renameConversation,
    autoTitleConversation,
    refreshConversations: fetchConversations,
  };
};
